language: python

matrix:
  include:
    - python: 3.5

install:
  pip3 install -r requirements.txt

script:
  - make docker-build

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo $DOCKER_PASSWORD | docker login -u="$DOCKER_USERNAME" --password-stdin;
      make docker-push;
    fi
