name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: adcrinis/homematicip-exporter

    - name: Timestamp
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 
          latest
          ${{ steps.date.outputs.date }}
        labels: ${{ steps.meta.outputs.labels }}
